import { Roboto } from 'next/font/google'
import "./globals.css";
import Navbar from "@/component/shared/Navbar";
import "daisyui/dist/full.css";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={roboto.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
